name: CI

on:
  push:
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: registry.opensuse.org/home/okurz/container/containers/tumbleweed:logwarn
    steps:
      - uses: actions/checkout@v2

      - name: Run unit tests
        run: prove -v ./test_logwarn
